export {default as HomePage} from './HomePage'
export {default as HeroesPage} from './HeroesPage'
export {default as HeroPage} from './HeroPage'
export {default as NotFoundPage} from './NotFoundPage'
export {default as SearchPage} from './SearchPage'